version: "3.8"

services:
  db:
    image: postgres:16
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - vnetdocs

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: medcol-backend:latest
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET}
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - AZURE_STORAGE_CONTAINER_NAME=${AZURE_STORAGE_CONTAINER_NAME}
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - AZURE_STORAGE_ACCOUNT_KEY=${AZURE_STORAGE_ACCOUNT_KEY}
    depends_on:
      - db
    networks:
      - vnetdocs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.medcol-backend.rule=Host(`medcoldocs.jhamf.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.medcol-backend.entrypoints=websecure"
      - "traefik.http.routers.medcol-backend.tls.certresolver=myresolver"
      - "traefik.http.services.medcol-backend.loadbalancer.server.port=4000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://medcoldocs.jhamf.com/api
    image: medcol-frontend:latest
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - backend
    networks:
      - vnetdocs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.medcol-frontend.rule=Host(`medcoldocs.jhamf.com`)"
      - "traefik.http.routers.medcol-frontend.entrypoints=websecure"
      - "traefik.http.routers.medcol-frontend.tls.certresolver=myresolver"
      - "traefik.http.services.medcol-frontend.loadbalancer.server.port=3000"

volumes:
  pgdata:


networks:
  vnetdocs:
    external: true
